# https://taskfile.dev
version: "3"
tasks:
  default: mix test
  sh: iex --erl "-kernel shell_history enabled" -S mix

  pub:
    desc: publish package
    cmds:
      - mix hex.publish --yes --replace

  # mix hex.publish package
  pub-docs: mix hex.publish docs --yes
  # HEX_API_KEY=xxx mix hex.publish --yes

  ## Git ops
  cmt: mix git_ops.release --yes && git push --follow-tags
  app-info: mix git_ops.project_info
  init-release: mix git_ops.release --initial
