# https://taskfile.dev/usage/
version: "3"
tasks:
  default: mix test
  sh: iex --erl "-kernel shell_history enabled" -S mix

  pub:
    desc: publish hex package
    env:
      HEX_API_KEY: $HEX_API_KEY
    cmds:
      - mix hex.publish --yes --replace
  pub-docs: mix hex.publish docs --yes

  ## Git ops
  cmt: mix git_ops.release --yes && git push --follow-tags
  app-info: mix git_ops.project_info
  init-release: mix git_ops.release --initial
