# https://taskfile.dev
version: "3"
tasks:
  default: mix test
  sh: iex --erl "-kernel shell_history enabled" -S mix

  pub:
    desc: publish package
    cmds:
      - mix hex.publish --yes --replace
  # mix hex.publish package
  pub-docs: mix hex.publish docs --yes
