# https://taskfile.dev/usage/
version: "3"
vars:
  httpcSrcUrl: https://raw.githubusercontent.com/cao7113/req_client/refs/heads/main/notes/httpc.ex
includes:
  c: ./Taskfile-cluster.yml

tasks:
  default: mix test
  #  --dbg pry
  sh: iex --erl "-kernel shell_history enabled" -S mix

  build: |
    mix build
    ls -l _build/*.ez
  up: mix up

  # chmod +x run/**/*.exs
  # chmod +x script/**/*.exs
  # iex -S mix test test/hello_elixir_test.exs:6 -b
  slow-test: mix test --slowest 10
  stale-test: mix test --stale
  # https://hexdocs.pm/mix/Mix.Tasks.Test.html#module-file-system-watchers
  smart-test: fswatch lib test | mix test --listen-on-stdin --stale

  hc.copy: |
    mix h.hc.mget {{.httpcSrcUrl}} > lib/ehelper/httpc.ex
    mix format
  hc.get: 
    mix h.hc.mget {{.httpcSrcUrl}}

  rel: mix release --overwrite --force

  pub:
    desc: publish hex package
    env:
      HEX_API_KEY: $HEX_API_KEY
    cmds:
      - mix hex.publish --yes --replace
  pub.docs: mix hex.publish docs --yes
  docs: mix docs
  # https://www.erlang.org/doc/apps/inets/http_server.html#serving-files-from-the-command-line
  sdoc: erl -S httpd serve doc

  ## Git ops
  ops.up: mix git_ops.release --yes && git push --follow-tags
  prj.info: mix git_ops.project_info
  ops.init: mix git_ops.release --initial

  deps: |
    mix do up + h.deps
  
  setup: |
    mise install
    mix deps.get

    mix local.hex --force --if-missing
    mix archive.install hex phx_new --force
    
  v: |
    elixir -v 
    # elixir --version