defmodule Mix.Tasks.H.Deps.Links.Tmpl do
  @shortdoc "Generate deps local-linking template"

  @moduledoc """
  #{@shortdoc}.

  Generate template content to copy into your mix.exs file
  """

  use Mix.Task

  @impl true
  def run(_args) do
    shell = Mix.shell()
    content = tmpl_content()
    shell.info(content)

    shell.info(
      "\n\n # reploace deps: deps(), with deps: deps_with_linking_path(), in def project() in mix.exs"
    )
  end

  defp tmpl_content do
    ~S"""
    ## Support deps local-linking, generated by task: mix h.deps.links.templ
    def raw_deps, do: deps()

    def deps_with_linking_path(deps \\ deps()) do
      # Mix.Local.append_archives()
      # :code.get_path() |> Enum.sort()

      Mix.DepLink
      |> Code.ensure_loaded()
      |> case do
        {:module, _} ->
          deps
          |> Mix.DepLink.deps_with_local_linking()

        {:error, reason} ->
          if Mix.env() in [:dev, :test] do
            Mix.raise(
              "Not found Mix.DepLink because: #{reason |> inspect}, please run: mix archive.install hex ehelper first!"
            )
          else
            deps
          end
      end
    end
    """
  end
end
